### ISSUE TITLE
no icons displayed & change temp

### ISSUE THREAD

**Issue by t0m5k1** [demure/dotfiles#1]
Hi Demure,
thanks for the intro to you version of the bar however I seem to not get icons regardless of the font used in the config.
When I start the script manually I get the following:

 t0m5k1  ~  sh .i3/lemonbar/i3_lemonbar.sh                                                                                                                                                     143 
conky: Syntax error (.i3/lemonbar/i3_lemonbar_conky:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
^C[1]    15181 terminated  sh .i3/lemonbar/i3_lemonbar.sh
 t0m5k1  ~  ./.i3/lemonbar/i3_workspaces.pl                                                                                                                                                    143 
Wide character in print at ./.i3/lemonbar/i3_workspaces.pl line 130.
WSPFOC INA 
Wide character in print at ./.i3/lemonbar/i3_workspaces.pl line 130.
WSPINA FOC 
Wide character in print at ./.i3/lemonbar/i3_workspaces.pl line 130.
WSPFOC INA 

This results in a bar that looks like this:
![screenshot_2016-03-11_08-02-11](https://cloud.githubusercontent.com/assets/1597399/13696644/97c9f214-e75f-11e5-8e29-508162ecf6dd.png)

I commented out some items within the parser that I do not need/want using # & made the following changes to the config:

font="DejaVu Sans Mono-8"
iconfont="PowerlineSymbols-8"
# iconfont="fontawesome-10"

res_w=$(xrandr | grep "current" | awk '{print $8a}')

As well as the above can you tell me how to change the temp to Celsius?

thanks for all your efforts & I hope to get this working soon.

**Comment by t0m5k1** [comment]
also when I run the script from terminal & change workspace I get the following error:

xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
Wide character in print at .i3/lemonbar/i3_workspaces.pl line 130.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.

**Comment by demure** [comment]
Closed as I have moved to polybar, and my notabug is my main instance of this repo.
